name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - feature/lab4-actions
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow works"